### ISSUE TITLE
150x3mm UK Alternative 

### ISSUE THREAD

**Issue by phillipsnick** [Makerr-Studio/CentrifugalDustSeparator-#5]
Just received 2x 500mm lengths of this https://plasticonline.co.uk/150mm-diameter-clear-acrylic-tube.html here in the UK.

Some quick tests with my callipers 

- Wall thickness: 3.1mm
- OD: 150.05mm
- ID: 144.16mm

Noticed you have plans to release EU versions of the files in the future. If you need help with any test prints against these sizes let me know. 

I was going to scale the original models, but if you have plans for specific versions it probably makes sense to wait!

**Comment by Makerr-Studio** [comment]
Hi phillipsnick,

I received these tubes: https://www.kunststofforte.nl/product/transparante-acrylaat-buizen-xt/ here in the Netherlands.

I already adjusted the files to my dimensions:
- Wall thickness: 3.5 mm
- OD: 151,375 mm
- ID: 144,375 mm

The files are already printed. I just need to assemble all the parts and film the process. I will share the files with you, so you can check you are able to scale them to fit your tube. If not, I can adjust the parts for a UK version :D.

**Comment by Makerr-Studio** [comment]
Hi phillipsnick,

I adjusted my files to your measurements. See the Step files:
https://github.com/Makerr-Studio/CentrifugalDustSeparator-/tree/main/MK2_UK"

Y-peaces are the same as MK2. 

You need to check if the parts / O-rings will fit. I can adjust the files with your feedback if necessary.

**Comment by phillipsnick** [comment]
Amazing @Makerr-Studio appreciate it!

I'll do some test prints at some point in the next week and report back :) Looking forward to seeing this thing in action

**Comment by phillipsnick** [comment]
Managed to squeeze a few prints in to test this.

Scale ring fits snug at the 0 marker. 👍 

Printed a few other parts to check fits

- Inlet/outlet port fit snug
- Y inlet/outlet (125mm version) fit perfectly

![IMG_2114](https://github.com/user-attachments/assets/0b0788a6-b72c-49f7-93d9-b5d893e2b2ed)

Noticed a couple of issues:

- [ ] [MK2_UK_impeller-shroud.stp](https://github.com/Makerr-Studio/CentrifugalDustSeparator-/blob/main/MK2_UK/STEP/MK2_UK_impeller-shroud.stp) is missing a o ring cut out? 
- [] [MK2_UK_port-A-cutting-jig.stp](https://github.com/Makerr-Studio/CentrifugalDustSeparator-/blob/main/MK2_UK/STEP/MK2_UK_port-A-cutting-jig.stp) and [MK2_UK_port-B-cutting-jig.stp](https://github.com/Makerr-Studio/CentrifugalDustSeparator-/blob/main/MK2_UK/STEP/MK2_UK_port-B-cutting-jig.stp) haven't exported properly (see screenshot below) 

<img width="1495" alt="Screenshot 2024-08-09 at 18 48 14" src="https://github.com/user-attachments/assets/83e855ae-57f7-423e-9bde-f139e1bbb169">

<img width="631" alt="Screenshot 2024-08-09 at 18 51 04" src="https://github.com/user-attachments/assets/1c367a53-fb08-406f-80f9-4221af1b63db">

**Comment by Makerr-Studio** [comment]
Great to see the first parts fit perfectly! 

I had removed the O-ring from the Impeller Shroud in the EU design I am building right now. I don't think the added value of the o-ring is really there if the shroud fits perfectly snug. And I have noticed that this also makes assembly a lot easier without.

Because you also use Bambu Lab slicer I just add two new folders to the MK2_UK folder. 
- One with all the Bambu Lab files with the settings I did use myself, adjusted for the UK version. Also add a file for the Impeller Shroud with O-ring cut out.
- And one for the OrcaSlicer file for better print results of the mirrored impeller. Just in case you like to replicate the mirrored look. Printing two times the normal impeller setup works fine as well.

I did not had problems importing the cutting jigs into my slicer. Used the same STEP-files for that.

Please let me know if you need something else.

**Comment by phillipsnick** [comment]
Makes sense regarding the O-ring, also can imagine it makes it a little bit more difficult to insert the part inside the tube.

Thanks for those files, they worked great. Not sure why when I was importing into OrcaSlicer they were coming out like that.

I had to scale down [MK2_UK_impeller-shroud.3mf](https://github.com/Makerr-Studio/CentrifugalDustSeparator-/blob/main/MK2_UK/BAMBU%20LAB/MK2_UK_impeller-shroud.3mf) (along with the impeller) to 99.9 as at 100% it was just too snug to push further down the tube past the opening. Which might be worth a note in the README?

Huge thanks for all your work on this 😁 you should add a donate link for some coffee/beer/PLA money.

I've printed all the parts, just need to figure out the cuts on the tubes and get it all bolted down!

![IMG_2176](https://github.com/user-attachments/assets/a7256bbb-2e49-4f9e-bd46-6802e5feb910)

**Comment by Makerr-Studio** [comment]
Hi Nick!

Great to see it worked for you! I added files for the cutting jigs you can print and use as a cutting guide. Please be careful with the acrylic tube! It is in no way flexible as the PVC tube. 

Don’t ask how I know 😅.

I used a oscillating multi tool to cut the acrylic. Use a blade with big teeth. Acrylic like to melt if not properly removed. I used a hardwood blade.
And protect yourself against toksick fumes of the acrylic and the hot chips.

Did your O-rings fit? I am building my EU design for video. Only had to order new smaller O-ring 120x3mm because the 140x3 are way to big in diameter and was a nightmare to fit inside the tube. Needed to reprint the in and outlets for that. You managed the fit as far I can see on your photo.

Please donate Tim from Philson Guitar! Without his work I would have been able to make mine version. Chears!
